apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  serviceName: mongo
  replicas: 3
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: us-central1-docker.pkg.dev/inlaid-contact-466616-g2/ip4repo/mongo:1.0.0
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes: [ "ReadWriteMany" ]
      storageclassName: sc
      resources:
        requests:
          storage: 5Gi
