---
# tasks file for backend-deployment
   - name: Build backend image
     docker_image: 
       name: yolo_backend
       source: build
       build:
         path: "ip3/backend"
   
   - name: Run backend container
     docker_container:
       name: yolo_backend
       image: yolo_backend
       state: started
       restart_policy: always
       networks:
         - name: ansinet
       env:
         MONGODB_URI: mongodb://mongo_container:27017/yolomy
         DBNAME: yolomy
       ports:
         - "5000:5000"
