---
# tasks file for deployment


- name: Basic deploy of a service
  community.general.terraform:
    project_path: "{{ playbook_dir }}"
    state: present
    force_init: true
  delegate_to: localhost
  become: false 
  
